# First CRD: MyApp
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: myapps.example.com
spec:
  group: example.com
  names:
    kind: MyApp
    plural: myapps
    singular: myapp
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          $ref: "#/components/schemas/MyAppSpec"

---

# Second CRD: MyDatabase
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mydatabases.example.com
spec:
  group: example.com
  names:
    kind: MyDatabase
    plural: mydatabases
    singular: mydatabase
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          $ref: "#/components/schemas/MyDatabaseSpec"

---

# Shared Components Section
components:
  schemas:
    MyAppSpec:
      type: object
      properties:
        name:
          type: string
        database:
          $ref: "#/components/schemas/MyDatabaseSpec"

    MyDatabaseSpec:
      type: object
      properties:
        host:
          type: string
        port:
          type: integer
