apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: myapps.example.com
spec:
  group: example.com
  names:
    kind: MyApp
    plural: myapps
    singular: myapp
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              $ref: '#/components/schemas/MyAppSpec'
components:
  schemas:
    MyAppSpec:
      type: object
      properties:
        appName:
          type: string

---

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mydatabases.example.com
spec:
  group: example.com
  names:
    kind: MyDatabase
    plural: mydatabases
    singular: mydatabase
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              $ref: '#/components/schemas/MyDatabaseSpec'
components:
  schemas:
    MyDatabaseSpec:
      type: object
      properties:
        host:
          type: string
        port:
          type: integer
